import pygame as pg
INITIAL_WIDTH = 800
INITIAL_HEIGHT = 500
COMPONENTS_FOLDER_PATH = r"source\components"
INITIAL_VIEWPORT_SIZE = (INITIAL_WIDTH, INITIAL_HEIGHT)

ADD_ELEMENT_EVENT = pg.USEREVENT + 1

NAME = "ScriptFrame"